### ISSUE TITLE
There is no description on how to change the mode vcpkg runs in.

### ISSUE THREAD

**Issue by aljohnston112** [microsoft/vcpkg-docs#104]
I am a vcpkg noob, so I followed the install instructions VS 2022 linked to here: https://vcpkg.io/en/getting-started.html
 I installed a package in classic mode, and then when I restarted the console, vcpkg switched to manifest mode, and it would be nice to have docs that tell you how to switch modes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9263b09a-d6a7-229d-8e9d-9b8b1fae7c18
* Version Independent ID: 9263b09a-d6a7-229d-8e9d-9b8b1fae7c18
* Content: [Classic mode](https://learn.microsoft.com/en-us/vcpkg/users/classic-mode)
* Content Source: [vcpkg/users/classic-mode.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/users/classic-mode.md)
* Product: **vcpkg**
* GitHub Login: @ras0219-msft
* Microsoft Alias: **roschuma**

**Comment by Neumann-A** [comment]
the switch between manifest mode and classic mode is only a question of having a manifest (`vcpkg.json`) visible to vcpkg or not.
visible depends on the integration your are using but in general it is manifest in CWD or any parent folder.
