### ISSUE TITLE
Ubuntu 16.04 FAQ reference may be outdated

### ISSUE THREAD

**Issue by kennylevinsen** [microsoft/vcpkg-docs#125]
The vcpkg FAQ states that continuous testing targets Ubuntu 16.04. It is possible that this statement is out of date considering that standard support for Ubuntu 16.04 (and 18.04 for that matter) has expired.

It would be good to know what the current support target is.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bdc4f66-0014-e830-24d0-1b462e44b7c3
* Version Independent ID: 9bdc4f66-0014-e830-24d0-1b462e44b7c3
* Content: [Frequently Asked Questions](https://learn.microsoft.com/en-us/vcpkg/about/faq)
* Content Source: [vcpkg/about/faq.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/about/faq.md)
* Product: **vcpkg**
* GitHub Login: @vicroms
* Microsoft Alias: **viromer**

**Comment by AugP** [comment]
Thanks for reporting this issue! I have made a number of FAQ changes and I fixed this as well in a PR. The current tested target is Ubuntu 22.04. I'll try to close out the PR as soon as possible.
