### ISSUE TITLE
Rename VCPKG_MAKE_CONFIGURE_OPTIONS -> VCPKG_CONFIGURE_MAKE_OPTIONS not documented

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vcpkg-docs#137]
I just spend 2 hours two build vcpkg cppunit package with llvm libc++. It is build is make/automake based.

Documentation says i should modify `VCPKG_MAKE_CONFIGURE_OPTIONS` in my custom triplet but this had no affect. So I went digging into the vcpkg code and learned that this was renamed in [PR#20165](https://github.com/microsoft/vcpkg/pull/20165). Missing documentation was already posted [there ](https://github.com/microsoft/vcpkg/pull/20165#issuecomment-1223428459) but no one took action.

Therefore I open this issue in hope this will be changed and future users do not need to do the same digging as I did.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81b81fec-b84b-3943-0b8b-4d3c6c8a17cd
* Version Independent ID: 81b81fec-b84b-3943-0b8b-4d3c6c8a17cd
* Content: [Triplet files](https://learn.microsoft.com/en-us/vcpkg/users/triplets)
* Content Source: [vcpkg/users/triplets.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/users/triplets.md)
* Product: **vcpkg**
* GitHub Login: @vicroms
* Microsoft Alias: **viromer**

**Comment by Neumann-A** [comment]
I think https://github.com/microsoft/vcpkg/pull/20165 got it wrong.

**Comment by KUGA2** [comment]
> I think [microsoft/vcpkg#20165](https://github.com/microsoft/vcpkg/pull/20165) got it wrong.

No, I think the rename in this PR is correct. The variable names usually reflect the function it is used in. In this case `vcpkg_configure_make()`. And the function name is also the same shema as other configure functions.

![image](https://github.com/microsoft/vcpkg-docs/assets/10581931/6fa724a1-dabf-4114-ad15-b9c346fbe09e)

**Comment by Neumann-A** [comment]
Nonsense. I introduced the variable.... as well as `VCPKG_CMAKE_CONFIGURE_OPTIONS`. It was intended to be parallel and consistent to it which is why it is `VCPKG_MAKE_CONFIGURE_OPTIONS`

`VCPKG_CMAKE_CONFIGURE_OPTIONS` is also used in `vcpkg_configure_cmake`. It has nothing to do with the function name.

**Comment by KUGA2** [comment]
Ok. So should I open a issue there?

**Comment by vicroms** [comment]
While I agree with @Neumann-A that these variables should have the same pattern, we have to document what currently works.
