### ISSUE TITLE
A couple of problems

### ISSUE THREAD

**Issue by production-robots** [microsoft/vcpkg-docs#181]
1. 
cmake presets=default 

should be 
cmake preset=default

2.
On my (windows) system $ENV in CMakePresets.json must be lower case, as stated in the CMake docs

"CMAKE_TOOLCHAIN_FILE": "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"

should be
"CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5099d71b-6e6f-f2d6-ab3f-3e8327541245
* Version Independent ID: 5099d71b-6e6f-f2d6-ab3f-3e8327541245
* Content: [Install and use packages with CMake](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started)
* Content Source: [vcpkg/get_started/get-started.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started.md)
* Product: **vcpkg**
* GitHub Login: @JavierMatosD
* Microsoft Alias: **javiermat**

**Comment by BillyONeal** [comment]
RE: 2:

ENV is documented to be caps:
https://cmake.org/cmake/help/latest/variable/ENV.html

but the env *macro* in presets is documented lowercase: https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#macro-expansion

Thanks for the consistency CMake 😭

**Comment by production-robots** [comment]
Now I come to think of it, I am sure I have used $ENV before in a different context. Whether we like it or not, I think we can all agree CMake is a bit of a minefield. 

The second page you quoted was my source for "as quoted in the CMake docs"
