### ISSUE TITLE
The CMakePresets.json file presented in the text is incompatible with the CMake shipped with VS 2019 (latest)

### ISSUE THREAD

**Issue by mcginnie** [microsoft/vcpkg-docs#204]
In the documentation on how to use vcpkg the CMakePresets.json file uses a version 3 schema.
This schema type is available only with Cmake version 3.21, while the version shipped with VC 2019 is 3.20, and therefore the
subsequent 

cmake --preset=default

fails with the error "Invalid preset".

Please either:
1) Add a pre-requisites section indicating the need for a newer CMake (and link to instructions on how to install a more modern cmake)
2) Correct the CMakePresets.json file to be compatible with version 2 schema
3) Arrange for an update to the Cmake in 2019 (and others) so that the json file successfully processes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5099d71b-6e6f-f2d6-ab3f-3e8327541245
* Version Independent ID: 5099d71b-6e6f-f2d6-ab3f-3e8327541245
* Content: [Install and use packages with CMake](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started)
* Content Source: [vcpkg/get_started/get-started.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started.md)
* Product: **vcpkg**
* GitHub Login: @JavierMatosD
* Microsoft Alias: **javiermat**

**Comment by AugP** [comment]
Closing as the schema version seems to have been updated to 2 a while ago.
