### ISSUE TITLE
Further problems with CMakePresets.json and Cmake

### ISSUE THREAD

**Issue by mcginnie** [microsoft/vcpkg-docs#205]
Following up on the previous comment.
The VS 2019 included CMake doesn't work with the CMakePresets.json file specified.
I then tried a new install of the latest Cmake (3.28.0-rc3) but the command

cmake --preset=default

gives the different error:
Preset "default" missing field "generator"
Invalid preset: "default"

If I knew the details of how to fix things like this I would not be following a basic tutorial on using vcpkg - so I have no idea what to do now, and it seems that this page if of no value to VS 2019 Enterprise users.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5099d71b-6e6f-f2d6-ab3f-3e8327541245
* Version Independent ID: 5099d71b-6e6f-f2d6-ab3f-3e8327541245
* Content: [Install and use packages with CMake](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started)
* Content Source: [vcpkg/get_started/get-started.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started.md)
* Product: **vcpkg**
* GitHub Login: @JavierMatosD
* Microsoft Alias: **javiermat**

**Comment by vicroms** [comment]
Hi @mcginnie 

By taking a look at the CMake documentation I noticed we can reduce the schema requirement for `CMakePresets.json` to version 1, and this would help users with older CMake.

In your case, the following CMakePresets.json should work:

```json
{
  "version": 1,
  "configurePresets": [{
    "name": "default",
    "generator": "Ninja",
    "binaryDir": "${sourceDir}/build",
    "cacheVariables": {
      "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
    }
  }]
}
```

From the top of my mind I can't remember if VS 2019 comes with Ninja, but if that doesn't work then you can set the `generator` to [`Visual Studio 16 2019`](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2016%202019.html)

**Comment by AugP** [comment]
Closing this as users migrate to newer versions of CMake over time, in which case they may prefer to be on a newer schema version. Since we haven't gotten other reports about this issue with the tutorial we will leave it alone for now.
