### ISSUE TITLE
Tutorial: Create and publish packages is outdated

### ISSUE THREAD

**Issue by BewareMyPower** [microsoft/vcpkg-docs#225]
https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-packaging

```bash
vcpkg install vcpkg-sample-library --overlay-ports=C:\path\to\custom-overlay
```

The command above does not work for the example in [Install and use packages with vcpkg](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started), which now uses manifest mode to build a project.

The correct solution should be adding the "overlay-ports" section to `vcpkg-configuration.json`:

```json
{
  "default-registry": {
    "kind": "git",
    "baseline": "45f6e57d3e10ad96b7db206cf7888f736ba5aa61",
    "repository": "https://github.com/microsoft/vcpkg"
  },
  "registries": [
    {
      "kind": "artifact",
      "location": "https://github.com/microsoft/vcpkg-ce-catalog/archive/refs/heads/main.zip",
      "name": "microsoft"
    }
  ],
  "overlay-ports": [
    "../custom-overlay/vcpkg-sample-library"
  ]
}
```

BTW, all these two documents mentioned `main.cpp` but the source file is `helloworld.cpp`. See https://learn.microsoft.com/en-us/vcpkg/get_started/get-started?pivots=shell-bash#3---add-dependencies-and-project-files

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8d2112b-8112-9f5a-7d19-c472e07e739f
* Version Independent ID: f8d2112b-8112-9f5a-7d19-c472e07e739f
* Content: [Tutorial: Packaging a library](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-packaging)
* Content Source: [vcpkg/get_started/get-started-packaging.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started-packaging.md)
* Product: **vcpkg**
* GitHub Login: @JavierMatosD
* Microsoft Alias: **javiermat**

**Comment by BewareMyPower** [comment]
BTW, I configured out the solution from the document of overlay ports: https://learn.microsoft.com/en-us/vcpkg/concepts/overlay-ports

**Comment by roysc** [comment]
This tutorial also neglects to mention that the new package must be added to the manifest in the dependent project. I've opened a PR to patch this.
