### ISSUE TITLE
The prerequisites are not documented well

### ISSUE THREAD

**Issue by BewareMyPower** [microsoft/vcpkg-docs#230]
From https://vcpkg.io/en/getting-started.html, we can see the prerequisites are:
- Git
- g++ >= 6

However, `./vcpkg/bootstrap-vcpkg.sh` has more prerequisites from the `vcpkg-bootstrap.log`:

```
Could not find curl. Please install it (and other dependencies) with:
On Debian and Ubuntu derivatives:
  sudo apt-get install curl zip unzip tar
On recent Red Hat and Fedora derivatives:
  sudo dnf install curl zip unzip tar
On older Red Hat and Fedora derivatives:
  sudo yum install curl zip unzip tar
On SUSE Linux and derivatives:
  sudo zypper install curl zip unzip tar
On Arch Linux and derivatives:
  sudo pacman -S curl zip unzip tar cmake ninja
On Alpine:
  apk add build-base cmake ninja zip unzip curl git
  (and export VCPKG_FORCE_SYSTEM_BINARIES=1)
```

```
Unable to determine a binary release of vcpkg; attempting to build from source.
Building vcpkg-tool...
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.15 or higher is required.  You are running version 3.13.4
```

i.e. to use vcpkg we also need:
- curl
- zip
- unzip
- tar
- ninja
- cmake >= 3.15

**Comment by dg0yt** [comment]
For common x64 linux installations, a vcpkg binary is downloaded, not build from source. Some other binaries are download, too. In these cases, the vcpkg CMake toolchain can be used with CMake 3.7.
For other installations such as arm64, the vcpkg binary is build from source, and some other binaries are expected to come from the system. The requirements are more modern in this case.

For building vcpkg ports, additional (or newer) tools are needed, too.

**Comment by AugP** [comment]
Closing as the old link is out of date and replaced by our newer docs. See: https://learn.microsoft.com/en-us/vcpkg/concepts/supported-hosts
