### ISSUE TITLE
Dead link to "Manifest mode: CMake Example"

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg-docs#240]
Hi,

I was looking for an example of how to use vcpkg.json (Manifest mode) with CMake from the command-line (i.e. without the Visual Studio IDE). This page https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/installing-and-using-packages.md refers to a promising example ("Manifest mode: CMake Example") but the link https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/manifest-mode-cmake.md is unfortunately a 404.

**Comment by vicroms** [comment]
@patrikhuber 

Thanks for the report, the articles you linked are old. 
Did you get to them through the main repository's README? 

The new "Get Started" series of articles should help you out: https://learn.microsoft.com/vcpkg/get_started/get-started

**Comment by AugP** [comment]
Closing this as it appears to be addressed.
