### ISSUE TITLE
error: this vcpkg instance requires a manifest with a specified baseline in order to interact with ports.

### ISSUE THREAD

**Issue by AmiramSella** [microsoft/vcpkg-docs#258]
Hi
I did the instructions , but I got an error:
error: this vcpkg instance requires a manifest with a specified baseline in order to interact with ports. Please add 'builtin-baseline' to the manifest or add a 'vcpkg-configuration.json' that redefines the default registry.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09fd1386-6491-3c4e-8704-e25c041d540a
* Version Independent ID: 09fd1386-6491-3c4e-8704-e25c041d540a
* Content: [Tutorial: Install a dependency from a manifest file](https://learn.microsoft.com/en-us/vcpkg/consume/manifest-mode?tabs=msbuild%2Cbuild-MSBuild)
* Content Source: [vcpkg/consume/manifest-mode.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/consume/manifest-mode.md)
* Service: **vcpkg**
* GitHub Login: @vicroms
* Microsoft Alias: **viromer**

**Comment by vicroms** [comment]
Hi @AmiramSella 
Thanks for the report, I need a bit of information. I suspect that this happened with the vcpkg version that is bundled with Visual Studio. Can you confirm whether that's the case? Or did this happen with a standalone vcpkg install (git clone + bootstrap)?

The fix would be to specify in the tutorial that this method is intended to work with vcpkg' standalone version. And to add an entry with this error message to the "Troubleshoot package failures" article with instructions to fix the issue.

**Comment by ignotus87** [comment]
I am using a fresh Ubuntu WSL (Windows Subsystem for Linux), I just installed VCPKG [following the instructions found here](https://learn.arm.com/learning-paths/microcontrollers/vcpkg-tool-installation/installation/).

After that, I tried to install mapnik based on the instructions [here](https://github.com/mapnik/mapnik/blob/master/INSTALL.mdhttps://github.com/mapnik/mapnik/blob/master/INSTALL.md).

Then I got the same error message.

**Comment by vicroms** [comment]
Hi @ignotus87 

### Short answer:

You need to create a manifest file (a file named `vcpkg.json`) and declare your dependencies in that file. See our tutorial to [install dependencies from a manifest file](https://learn.microsoft.com/vcpkg/consume/manifest-mode).

`my-project/vcpkg.json`

```json
{
  "dependencies": [ "mapnik" ]
}
```

### Long answer:

The instructions you followed, are intended for users who want to try the experimental *artifacts* feature.  The artifacts feature enables vcpkg to acquire and install build tools by specifying them in your `vcpkg-configuration.json` file, see [lines 14 to 20 on their example `vcpkg-configuration.json` file](<https://learn.arm.com/learning-paths/microcontrollers/vcpkg-tool-installation/config_creation/>).

The `vcpkg-init.cmd` script installs a read-only version of vcpkg, this means that commands that modify the vcpkg root folder are not allowed, for example, [`vcpkg install <package>` in classic mode](<https://learn.microsoft.com/vcpkg/concepts/classic-mode>). Instead, you need to install packages in manifest mode by creating a `vcpkg.json` file for your project ([see our tutorial on using manifest mode](https://learn.microsoft.com/vcpkg/consume/manifest-mode))

If you're looking to use vcpkg for general development, we recommend that you install a standalone version of vcpkg using the steps in our [Get Started tutorial](https://learn.microsoft.com/vcpkg/get_started/get-started).

I'll add this error message as part of our troubleshooting guide in #307
