### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by AxorusMT** [microsoft/vcpkg-docs#274]
### Type of issue

Typo

### Description

[Enter feedback here]
Formatting issue with code. Should be a simple fix haha.

### Page URL

https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-vscode

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started-vscode.md

### Document Version Independent Id

6402b87a-b33e-ebf5-01d2-a2d1115d6f2b

### Article author

@data-queue

### Metadata

* ID: 6402b87a-b33e-ebf5-01d2-a2d1115d6f2b 
* Service: **vcpkg**

**Comment by vicroms** [comment]
Hi @AxorusMT 

I think this should be fixed now.
