### ISSUE TITLE
vcpkg如何添加本地包

### ISSUE THREAD

**Issue by nsygh1** [microsoft/vcpkg-docs#309]
### Type of issue

Missing information

### Description

我要利用cmake混合编译opencv和libtorch，我的电脑上已经安装了opencv和libtorch库，但是我使用vcpkg管理包时，仍然需要重新下载。在使用文档中提供的指令时却报错需要使用经典模式才能使用这个命令，但是文档中建议使用清单模式，并未对经典模式进行深入讲解。而且在visual studio 2022中，我无法对cmake编译附加参数，在解决方案右键属性并未找到附加参数项。请问我应该如何使用vcpkg来管理我本地opencv和libtorch库，在项目中编译并运行？

### Page URL

https://learn.microsoft.com/zh-cn/vcpkg/get_started/get-started

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started.md

### Document Version Independent Id

5099d71b-6e6f-f2d6-ab3f-3e8327541245

### Article author

@JavierMatosD

### Metadata

* ID: 5099d71b-6e6f-f2d6-ab3f-3e8327541245 
* Service: **vcpkg**

**Comment by nsygh1** [comment]
> @nsygh1
> 
> Thanks for the report. Have you tried the instructions in: https://learn.microsoft.com/vcpkg/get_started/get-started-vs
> 
> Those instructions are specific for Visual Studio and CMake scenario and show how to create a manifest file with your dependencies.

非常感谢你的回复。
我在发布这条issue之前已经仔细阅读过相关文档，同时尝试了许多方法都失败了。
唯一可能行得通的办法是使用经典模式指定库安装目录，但是在你们的教程之中，并未说明如何使用经典模式。
同时，在你们清单模式的文档中我未找到指定库安装目录的方法。
Thank you very much for your reply.
 I have carefully read the relevant documentation before posting this issue, and tried many methods but failed.
 The only possible way to work is to use the classic mode to specify the library installation directory, but in your tutorial, there is no explanation on how to use the classic mode.
 At the same time, I did not find a way to specify the library installation directory in your list mode documentation.

**Comment by AugP** [comment]
Classic mode and manifest mode are independent ways of installing libraries. Classic mode installs libraries under your vcpkg installation directory, whereas manifest mode installs libraries where your manifest file is located. This tutorial is intended to be for manifest mode and thus does not include classic mode instructions. 

For more details, see: 
https://learn.microsoft.com/vcpkg/concepts/manifest-mode
https://learn.microsoft.com/vcpkg/concepts/classic-mode
