### ISSUE TITLE
This page requests the creation of main.cpp but all build files refer to HelloWorld.cpp

### ISSUE THREAD

**Issue by BradfordDJones** [microsoft/vcpkg-docs#311]
### Type of issue

Typo

### Description

This page's instruction requests the creation of main.cpp.
All build files refer to HelloWorld.cpp.
This results in the following error.

CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/vcpkg/scripts/buildsystems/vcpkg.cmake:598 (_add_executable):
  Cannot find source file:

    helloworld.cpp

### Page URL

https://learn.microsoft.com/en-us/vcpkg/get_started/get-started

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started.md

### Document Version Independent Id

5099d71b-6e6f-f2d6-ab3f-3e8327541245

### Article author

@JavierMatosD

### Metadata

* ID: 5099d71b-6e6f-f2d6-ab3f-3e8327541245 
* Service: **vcpkg**

**Comment by vicroms** [comment]
Thanks for the report!

**Comment by AugP** [comment]
I don't see this issue in the current version of this article. The only references to "HelloWorld" seem to be for the name of the project, not the name of the .cpp source file. It's possible this was fixed a while ago when someone did an edit pass through that tutorial, so I am closing this issue.
