### ISSUE TITLE
What is Ninja?

### ISSUE THREAD

**Issue by dbookstaber** [microsoft/vcpkg-docs#314]
### Type of issue

Code doesn't work

### Description

I'm running VSCode under Win10.  I followed https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-vscode?pivots=shell-cmd and when I try to run the Helloworld project I get 

> [cmake] CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

<details>
<summary>
Full output:
</summary>
```

[proc] Executing command: cmake --version
[proc] The command: cmake --version failed with error: Error: spawn cmake ENOENT
[proc] Executing command: cmake -E capabilities
[proc] The command: cmake -E capabilities failed with error: Error: spawn cmake ENOENT
[variant] Loaded new set of variants
[kit] Successfully loaded 4 kits from C:\Users\David\AppData\Local\CMakeTools\cmake-tools-kits.json
[presetController] Reading and validating the presets "file D:\Code\Ctest\CMakePresets.json"
[presetController] Successfully validated presets in D:\Code\Ctest\CMakePresets.json
[presetController] Reading and validating the presets "file D:\Code\Ctest\CMakeUserPresets.json"
[presetController] Successfully validated presets in D:\Code\Ctest\CMakeUserPresets.json
[proc] Executing command: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --version
[proc] Executing command: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E capabilities
[cms-client] Configuring using the "Ninja" CMake generator
[cms-client] Configuring using the "Ninja" CMake generator
[driver] Switching to package preset: __defaultPackagePreset__
[driver] Switching to workflow preset: __defaultWorkflowPreset__
[main] Configuring project: Ctest 
[cmake] CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:100 (message):
[cmake]   Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:3 (project)
[cmake] 
[cmake] 
[cmake] CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
[cmake] CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
[cmake] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
[cmake] Configuring incomplete, errors occurred!
[cms-driver] Error during CMake configure: 
	Error: Configuration failed.
	at CMakeServerClient.onMessage (c:\Users\David\.vscode\extensions\ms-vscode.cmake-tools-1.17.17\dist\main.js:55555:33)
	at CMakeServerClient.onMoreData (c:\Users\David\.vscode\extensions\ms-vscode.cmake-tools-1.17.17\dist\main.js:55528:18)
	at Socket.emit (node:events:517:28)
	at addChunk (node:internal/streams/readable:335:12)
	at readableAddChunk (node:internal/streams/readable:308:9)
	at Readable.push (node:internal/streams/readable:245:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```
</details>

### Page URL

https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-vscode

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started-vscode.md

### Document Version Independent Id

6402b87a-b33e-ebf5-01d2-a2d1115d6f2b

### Article author

@data-queue

### Metadata

* ID: 6402b87a-b33e-ebf5-01d2-a2d1115d6f2b 
* Service: **vcpkg**

**Comment by vicroms** [comment]
Thanks for the feedback! Ninja is a build tool (https://ninja-build.org/), the tutorials should be modified to list Ninja as a pre-requisite.

As a workaround, you can run `vcpkg fetch ninja`. The command will download a copy of Ninja for vcpkg to use, and you just need the resulting output to your PATH environment variable.

**Comment by GengGode** [comment]
Can I modify ninja to vs 2022? I still encountered some issues after trying to install ninja

> [proc] 执行命令: "C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_TOOLCHAIN_FILE=C:/Users/Public/Library/vcpkg/scripts/buildsystems/vcpkg.cmake -SC:/dev/pip-remake -BC:/dev/pip-remake/build -G Ninja
[cmake] -- Running vcpkg install
[cmake] Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
[cmake] Detecting compiler hash for triplet x64-windows...
[cmake] -- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:1080".
[cmake] Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
[cmake] The following packages will be built and installed:
[cmake]     fmt:x64-windows@10.2.1#2 -- C:\Users\Gen\AppData\Local\vcpkg\registries\git-trees\f6f4efa01a5e9ac627f0c6687af8b6b317fbbe42
[cmake]   * vcpkg-cmake:x64-windows@2024-04-18 -- C:\Users\Gen\AppData\Local\vcpkg\registries\git-trees\a10a94e8d0071ed4804d40d0f0f0c5e4e7180afd
[cmake]   * vcpkg-cmake-config:x64-windows@2022-02-06#1 -- C:\Users\Gen\AppData\Local\vcpkg\registries\git-trees\8d54cc4f487d51b655abec5f9c9c3f86ca83311f
[cmake] Additional packages (*) will be modified to complete this operation.
[cmake] Restored 3 package(s) from C:\Users\Gen\AppData\Local\vcpkg\archives in 93.1 ms. Use --debug to see more details.
[cmake] Installing 1/3 vcpkg-cmake-config:x64-windows@2022-02-06#1...
[cmake] Elapsed time to handle vcpkg-cmake-config:x64-windows: 5.18 ms
[cmake] vcpkg-cmake-config:x64-windows package ABI: c0c0d952981faf958ceacba505f37a2c847ca75a7dfd53b417beda2384e753b8
[cmake] Installing 2/3 vcpkg-cmake:x64-windows@2024-04-18...
[cmake] Elapsed time to handle vcpkg-cmake:x64-windows: 6.54 ms
[cmake] vcpkg-cmake:x64-windows package ABI: 2b198f90c414188f4b44ad851912d6bfbfb9c71afbabf5ef849027573f29152d
[cmake] Installing 3/3 fmt:x64-windows@10.2.1#2...
[cmake] Elapsed time to handle fmt:x64-windows: 91.9 ms
[cmake] fmt:x64-windows package ABI: f34bc68c855ceeffd6ea0501aa0a7392da8272c00f311e0ad073a244ddcc26db
[cmake] Total install time: 104 ms
[cmake] The package fmt provides CMake targets:
[cmake] 
[cmake]     find_package(fmt CONFIG REQUIRED)
[cmake]     target_link_libraries(main PRIVATE fmt::fmt)
[cmake] 
[cmake]     # Or use the header-only version
[cmake]     find_package(fmt CONFIG REQUIRED)
[cmake]     target_link_libraries(main PRIVATE fmt::fmt-header-only)
[cmake] 
[cmake] -- Running vcpkg install - done
[cmake] -- The C compiler identification is unknown
[cmake] -- The CXX compiler identification is unknown
[cmake] CMake Error at CMakeLists.txt:3 (project):
[cmake]   No CMAKE_C_COMPILER could be found.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
[cmake]   the compiler, or to the compiler name if it is in the PATH.
[cmake] 
[cmake] 
[cmake] CMake Error at CMakeLists.txt:3 (project):
[cmake]   No CMAKE_CXX_COMPILER could be found.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
[cmake]   to the compiler, or to the compiler name if it is in the PATH.
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!

**Comment by vicroms** [comment]
@GengGode yes you can use any generator you like. We recommend Ninja but the VS generators also work.

In your case Ninja did not work because the compilers are not set up on the environment, please try running the commands from a Developer PowerShell for Visual Studio. It sets up the build environment for you and even has a `ninja.exe` that comes bundled with Visual Studio on `PATH`.

**Comment by AugP** [comment]
Closing as this appears to be resolved.
