### ISSUE TITLE
 Platform expression documentation appears to be inaccurate

### ISSUE THREAD

**Issue by jeremy-rifkin** [microsoft/vcpkg-docs#318]
### Type of issue

Outdated article

### Description

The platform expression documentation https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/reference/vcpkg-json.md#-platform-expression indicates that `expr && expr` and `expr || expr` should be valid, however locally I found that this wasn't the case and it'd only allow single `&` or `|`:

```
~/Projects/vcpkg !19549 › ./vcpkg x-add-version cpptrace --overwrite-version
error: can't load port cpptrace
error: while loading /home/rifkin/Projects/vcpkg/ports/cpptrace/vcpkg.json:
$.supports (a platform expression): CONTROL:1:6: error: missing or invalid identifier
  on expression: !uwp&&!android
                      ^
~/Projects/vcpkg !19550 › ./vcpkg x-add-version cpptrace --overwrite-version
error: can't load port cpptrace
error: while loading /home/rifkin/Projects/vcpkg/ports/cpptrace/vcpkg.json:
$.supports (a platform expression): CONTROL:1:9: error: missing or invalid identifier
  on expression: (!uwp) && (!android)
                         ^
~/Projects/vcpkg !19550 › ./vcpkg x-add-version cpptrace --overwrite-version
error: can't load port cpptrace
error: while loading /home/rifkin/Projects/vcpkg/ports/cpptrace/vcpkg.json:
$.supports (a platform expression): CONTROL:1:8: error: missing or invalid identifier
  on expression: !(uwp || android)
                        ^
```

### Page URL

https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json#platform-expression

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/reference/vcpkg-json.md

### Document Version Independent Id

c9908f8f-fc4a-6ba6-65a0-c4f16fc1621d

### Article author

@vicroms

### Metadata

* ID: c9908f8f-fc4a-6ba6-65a0-c4f16fc1621d 
* Service: **vcpkg**

**Comment by vicroms** [comment]
The documentation was taken from the spec, but given that there are no tests for operators `&&` and `||` I think it's better to just remove them from the documentation.
