### ISSUE TITLE
Unconsistent use of repo

### ISSUE THREAD

**Issue by burkaykinik** [microsoft/vcpkg-docs#323]
In the following line, repo is Microsoft/vcpkg-docs.
https://github.com/microsoft/vcpkg-docs/blob/74b319db2d82418a112dfbd769a41df4f5a92787/vcpkg/get_started/get-started-packaging.md?plain=1#L160

whereas in the explanation of that line of code, it is said to be JavierMatosD/vcpkg-sample-library,
https://github.com/microsoft/vcpkg-docs/blob/74b319db2d82418a112dfbd769a41df4f5a92787/vcpkg/get_started/get-started-packaging.md?plain=1#L190

**Comment by vicroms** [comment]
Fixed in latest push to `live`. It should reflect in the website shortly.
