### ISSUE TITLE
Northwindtraders Compilation on Linux x64 (proxy issue)

### ISSUE THREAD

**Issue by gblikas** [microsoft/vcpkg-docs#327]
### Type of issue

Code doesn't work

### Description

Please see https://github.com/northwindtraders/beison/issues/2 for a full summary of the issue. 

### Page URL

https://learn.microsoft.com/en-us/vcpkg/consume/git-registries

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/consume/git-registries.md

### Document Version Independent Id

3bc69d08-55e5-438a-0749-aa183d326f5d

### Article author

@vicroms

### Metadata

* ID: 3bc69d08-55e5-438a-0749-aa183d326f5d 
* Service: **vcpkg**

**Comment by vicroms** [comment]
should be solved by #370
