### ISSUE TITLE
Missing demo code snippet

### ISSUE THREAD

**Issue by jbowringttp** [microsoft/vcpkg-docs#350]
### Type of issue

Missing information

### Description

Example code snippet under "Examples" is missing:
![image](https://github.com/microsoft/vcpkg-docs/assets/122635748/c93123ed-da65-4c83-a3c2-65d1c5a1ac90)

### Page URL

https://learn.microsoft.com/en-us/vcpkg/commands/format-manifest

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/commands/format-manifest.md

### Document Version Independent Id

10adff1e-2932-77a9-2f0f-1056168e8caa

### Article author

@JavierMatosD

### Metadata

* ID: 10adff1e-2932-77a9-2f0f-1056168e8caa 
* Service: **vcpkg**

**Comment by vicroms** [comment]
Fixed in latest push to `live`. It should reflect in the website shortly.
