### ISSUE TITLE
Clarify triplet naming requirements

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vcpkg-docs#383]
In https://github.com/microsoft/vcpkg/issues/10120 it became obvious that there is some confusion around how triplets should be named. The tool seems to have different naming rules in different places (see linked issue) I was trying to fix this before I realized that in contrast to port names, there is no documentation about triplet names.

**Comment by Neumann-A** [comment]
You can name your triplet however you want. There is no requirement for any name it just needs to be a valid filename. Should of course not contain regex characters, spaces or slashes. Because that probably fails since nothing guards against that.

**Comment by Thomas1664** [comment]
> You can name your triplet however you want.

Well, the new error message says something else:

```
.\vcpkg install fmt:valid_triplet.name               
error: expected the end of input parsing a package spec; this usually means the indicated character is not allowed to be in a package spec. Port, triplet, and feature names are all lowercase alphanumeric+hypens.
  on expression: fmt:valid_triplet.name
                          ^
```
