### ISSUE TITLE
Wrong Filename

### ISSUE THREAD

**Issue by paul-marquick** [microsoft/vcpkg-docs#386]
### Type of issue

Other (describe below)

### Description

Got this - add_executable(HelloWorld **main.cpp**) but you say to create  **helloworld.cpp**.

### Page URL

https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-vscode?pivots=shell-bash

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started-vscode.md

### Document Version Independent Id

6402b87a-b33e-ebf5-01d2-a2d1115d6f2b

### Article author

@data-queue

### Metadata

* ID: 6402b87a-b33e-ebf5-01d2-a2d1115d6f2b 
* Service: **vcpkg**

**Comment by vicroms** [comment]
Fixed in #404
