### ISSUE TITLE
No mention that you need to run VS code from the developer prompt

### ISSUE THREAD

**Issue by s7evinkelevra** [microsoft/vcpkg-docs#398]
### Type of issue

Code doesn't work

### Description

It appears that it is required to run VSCode from the developer prompt (or have a equivalent setup in the system path), otherwise the setup just doesn't work. Nowhere is this mentioned in the docs. I'm thinking i'm missing something obvious here, otherwise this would be a major oversight.

### Page URL

https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-vscode

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started-vscode.md

### Document Version Independent Id

6402b87a-b33e-ebf5-01d2-a2d1115d6f2b

### Article author

@data-queue

### Metadata

* ID: 6402b87a-b33e-ebf5-01d2-a2d1115d6f2b 
* Service: **vcpkg**

**Comment by vicroms** [comment]
Running from the VS command prompt is only necessary when using the Ninja generator, you can use the Visual Studio generators then it will find the compiler correctly even if not running from a VS command prompt. In any case, I've added a note about it at the top of the tutorial.
