### ISSUE TITLE
Wrong cpp file mentioned in the cmake

### ISSUE THREAD

**Issue by joykumarbera** [microsoft/vcpkg-docs#406]
### Type of issue

Typo

### Description

i was following this section https://learn.microsoft.com/en-in/vcpkg/get_started/get-started-vs?pivots=shell-cmd#3---set-up-the-project-files but the cpp file mentioned in the CMakeLists.txt and in the explanation both are different.

In the cmake file mentioned `add_executable(HelloWorld main.cpp)`
and later in the document mentioned `add_executable(HelloWorld helloworld.cpp)`

![Screenshot 2024-09-24 023007](https://github.com/user-attachments/assets/9f223c45-1cef-45fa-8906-774eebcb4986)

### Page URL

https://learn.microsoft.com/en-in/vcpkg/get_started/get-started-vs

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started-vs.md

### Document Version Independent Id

94e7a328-84e7-33e6-9e9f-9bb95cbd99cb

### Article author

@JavierMatosD

### Metadata

* ID: 94e7a328-84e7-33e6-9e9f-9bb95cbd99cb 
* Service: **vcpkg**

**Comment by vicroms** [comment]
Fixed in #404
