### ISSUE TITLE
Wrong .cpp filename in the code snippet

### ISSUE THREAD

**Issue by Some-Noob** [microsoft/vcpkg-docs#407]
### Type of issue

Code doesn't work

### Description

No.3 of step _3 - Set up the project files_, in the line:
`add_executable(HelloWorld main.cpp)`
"main.cpp" is used even though the source file is named "helloworld.cpp"
This causes the code execution to fail

### Page URL

https://learn.microsoft.com/en-gb/vcpkg/get_started/get-started-vs

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started-vs.md

### Document Version Independent Id

94e7a328-84e7-33e6-9e9f-9bb95cbd99cb

### Article author

@JavierMatosD

### Metadata

* ID: 94e7a328-84e7-33e6-9e9f-9bb95cbd99cb 
* Service: **vcpkg**

**Comment by vicroms** [comment]
Fixed in #404
