### ISSUE TITLE
f

### ISSUE THREAD

**Issue by eftw2** [microsoft/vcpkg-docs#413]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/vcpkg/get_started/overview

### Content source URL

https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/overview.md

### Document Version Independent Id

c038c76a-550b-9b30-215f-a2747465590b

### Article author

@AugP

### Metadata

* ID: c038c76a-550b-9b30-215f-a2747465590b 
* Service: **vcpkg**

**Comment by AugP** [comment]
Unclear where the typo is, so closing this issue. Feel free to respond though if you can provide specifics.

**Comment by eftw2** [comment]
I never reported a problem. I don’t remember doing it.Sent from my iPhoneOn Oct 15, 2024, at 5:04 PM, Augustin Popa ***@***.***> wrote:﻿
Unclear where the typo is, so closing this issue. Feel free to respond though if you can provide specifics.
