### ISSUE TITLE
Links in this page are broken.

### ISSUE THREAD

**Issue by StrapiHub** [microsoft/vcpkg-docs#44]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d34b8963-7f3f-fc36-2cbe-13fb2d22dff9
* Version Independent ID: d34b8963-7f3f-fc36-2cbe-13fb2d22dff9
* Content: [Android Support in vcpkg](https://learn.microsoft.com/en-us/vcpkg/users/platforms/android)
* Content Source: [vcpkg/users/platforms/android.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/users/platforms/android.md)
* Product: **vcpkg**
* GitHub Login: @ras0219-msft
* Microsoft Alias: **roschuma**

**Comment by GeoSpatialEngine** [comment]
https://learn.microsoft.com/en-us/vcpkg/users/platforms/android
