### ISSUE TITLE
[vcpkg-docs] original specs are gone

### ISSUE THREAD

**Issue by MonicaLiu0311** [microsoft/vcpkg-docs#47]
This issue is a duplicate of https://github.com/microsoft/vcpkg/issues/30274, originally initiated by @Neumann-A.

Folder `docs/specifications`  was removed without a proper replacement in `vcpkg-docs`. (especially `ports-overlay.md`)

**Comment by MonicaLiu0311** [comment]
BTW: The link [here](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#recommended-solutions) to `ports-overlay.md` is wrong.
```
set(USING_DOG 0)
message(STATUS "This version of LibContoso uses the Kittens backend. To use the Dog backend instead, create an overlay port of this with USING_DOG set to 1 and the `kittens` dependency replaced with `dog`.")
message(STATUS "This recipe is at ${CMAKE_CURRENT_LIST_DIR}")
message(STATUS "See the overlay ports documentation at https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md")
```

**Comment by vicroms** [comment]
Specifications were never meant to serve as documentation, their purpose was to discuss the design process of each feature. 

We are working on providing proper documentation articles for the missing topics. Registries and versioning are already covered and @dan-shaw is currently working on the overlay ports article.
