### ISSUE TITLE
Manifest docs: First example is not very clear

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg-docs#54]
Hi,

In the manifest docs https://learn.microsoft.com/en-us/vcpkg/users/manifests, the first example contains:

```
  "dependencies": [
    "boost-system",
    {
      "name": "cpprestsdk",
      "default-features": false
    },
    "libxml2",
    "yajl"
  ]
```

It's not clear to me, and not described in the text (as far as I can see), what this part does:
```
    {
      "name": "cpprestsdk",
      "default-features": false
    }
```
Is it a dependency on cpprestsdk, but one that's not part of the default features? So is this a short-hand notation for adding a feature called "cpprestsdk", so if one then does `vcpkg install my-application[cpprestsdk]` the cpprestsdk gets installed, otherwise it won't?

Also, unrelated, but on the same page, the final heading "Default Features", it explains what default features are in plain text, but not what the syntax is to specify that something is (or is not) a default feature in the `vcpkg.json` file?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 249966f4-5235-b31a-cdfd-007401b3315c
* Version Independent ID: 249966f4-5235-b31a-cdfd-007401b3315c
* Content: [Manifest mode](https://learn.microsoft.com/en-us/vcpkg/users/manifests)
* Content Source: [vcpkg/users/manifests.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/users/manifests.md)
* Product: **vcpkg**
* GitHub Login: @ras0219-msft
* Microsoft Alias: **roschuma**

**Comment by vicroms** [comment]
Thanks for pointing this out, I'll add an explanation on a PR soon.

To answer your question, `cpprestsdk` has a set of default features enabled when you install it (`compression`, and additionally only on Windows, `brotli`). 

See `cpprestsdk/vcpkg.json`: https://github.com/microsoft/vcpkg/blob/db0473513e5dc73ec6b6f431ff05d2f398eea042/ports/cpprestsdk/vcpkg.json#L57-L63

The `"default-features": false` property on the example manifest disables the default features, so only the base `cpprestsdk` library is depended upon, without any of the additional features.

**Comment by patrikhuber** [comment]
Hi @vicroms,

Thanks for the reply! Aah, that makes complete sense. After reading your explanation, it's now crystal clear. But I couldn't make the leap when just reading the docs back in April.

Thanks!
