### ISSUE TITLE
How to Create Overlay Port

### ISSUE THREAD

**Issue by davidmatson** [microsoft/vcpkg-docs#63]
The docs on vcpkg's git docs folder used to explain how to create an overlay port. Now, all docs point to the Overlay Ports section here, but there is no statement on what is needed in order to create an overlay port.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33fd7c78-2b2b-13d3-e9cf-b54e6eb6d900
* Version Independent ID: 33fd7c78-2b2b-13d3-e9cf-b54e6eb6d900
* Content: [Using Registries](https://learn.microsoft.com/en-us/vcpkg/users/registries#overlays)
* Content Source: [vcpkg/users/registries.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/users/registries.md)
* Product: **vcpkg**
* GitHub Login: @ras0219-msft
* Microsoft Alias: **roschuma**

**Comment by vicroms** [comment]
HI @davidmatson 

We recently added a [tutorial for patching a library using overlay ports](https://learn.microsoft.com/vcpkg/consume/install-locally-modified-package) and added the old documentation back in the [overlay ports concept article](https://learn.microsoft.com/vcpkg/concepts/overlay-ports).

I'd really appreciate your feedback on these articles.

**Comment by davidmatson** [comment]
@vicroms - thanks! overall that looks good to me - the biggest suggestion I'd have would be to include, perhaps prefer, a manifest mode option in addition to the vcpkg command line install.
