### ISSUE TITLE
Add documentation for vcpkg artifacts 

### ISSUE THREAD

**Issue by JonLiu1993** [microsoft/vcpkg-docs#82]
**Describe the bug**
There is currently no documentation how to use vcpkg artifacts. 

**Expected behavior**
Add documentation how to use vcpkg artifacts to https://learn.microsoft.com/en-us/vcpkg/. 

**Additional context**
There are blog posts like https://devblogs.microsoft.com/cppblog/vcpkg-artifacts/ and https://devblogs.microsoft.com/cppblog/vcpkg-may-2022-release-is-now-available/ and kind of https://github.com/microsoft/vcpkg-tool#vcpkg-artifacts

**Comment by AugP** [comment]
Update on this: our documentation for vcpkg artifacts is currently on hold as the team is focusing on other documentation action items currently. We plan to get artifacts documentation once we are done the other high priority work and resume investing more resources into the artifacts experience more broadly as a team.

**Comment by AugP** [comment]
Closing this as we are tracking it elsewhere.
