### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by davidmatson** [microsoft/vcpkg-docs#84]
Under "Can I get vcpkg integration for custom configurations?":
"before the Vcpk integration is loaded"

should be "vcpkg", not "Vcpk".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bdc4f66-0014-e830-24d0-1b462e44b7c3
* Version Independent ID: 9bdc4f66-0014-e830-24d0-1b462e44b7c3
* Content: [Frequently Asked Questions](https://learn.microsoft.com/en-us/vcpkg/about/faq)
* Content Source: [vcpkg/about/faq.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/about/faq.md)
* Product: **vcpkg**
* GitHub Login: @ras0219-msft
* Microsoft Alias: **roschuma**

**Comment by AugP** [comment]
Thank you for reporting this issue. The typo has been fixed and will be deployed live shortly.

**Comment by davidmatson** [comment]
@AugP - I see the changes in main but not on the site yet. Does someone need to hit a button to deploy the changes?

**Comment by vicroms** [comment]
The changes will be reflected when #161 gets merged
