### ISSUE TITLE
Wrong type for default-features

### ISSUE THREAD

**Issue by bradpechacek** [microsoft/vcpkg-docs#98]
I believe that in the table for top level items, the type given for default-features is wrong.
vcpkg seems to want an array of features instead of a bool.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9908f8f-fc4a-6ba6-65a0-c4f16fc1621d
* Version Independent ID: c9908f8f-fc4a-6ba6-65a0-c4f16fc1621d
* Content: [vcpkg.json Reference](https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json)
* Content Source: [vcpkg/reference/vcpkg-json.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/reference/vcpkg-json.md)
* Product: **vcpkg**
* GitHub Login: @ras0219-msft
* Microsoft Alias: **roschuma**

**Comment by vicroms** [comment]
Fixed by #114
